### ISSUE TITLE
Setting PUID and PGID via env

### ISSUE THREAD

**Issue by ptr727** [tribut/homeassistant-docker-venv#2]
Hi, running HA on Unraid.
Found this solution after trying to figure out how to get HA to run using the specified user and group.
Without HA honoring my user and group setting, it is very difficult to access edit the config files, as they are owned by root.

Tried your solution, I added "--user 99:100" to options, don't have git in console on unraid, so I just created the raw file, set ownership to 99:100 and allowed all r/w/x.
Seems to work fine.

Three questions:
1) I found the post below that makes it sound like the default HA docker honors PUID and GUID, but I don't think it does, all files are still owned by root.
https://community.home-assistant.io/t/ha-in-docker-config-folder-write-access-upgrade-via-portainer-questions/74459/3
Do you know if PUID and GUID is honored, maybe I did something wrong, or is it required to use --user 99:100?

2) Created file permissions are still 644, meaning only owner can edit, while directory default is group edit. This means that when I SSH/SFTP in to where the config volumes are, my root user cannot edit the config files. 
Is there any way to set default file permissions to 777 or user and group edit? 

3) Running as non-root, and using a specific UID for mapped volumes seems like such a common thing, why is it not supported in the default HA docker, or any chance you can get it added?

**Comment by tribut** [comment]
Downloading the file to `/config/docker/run` works fine. I just prefer using git, because it allows for easier updating.

As for your questions:
1. PUID/GUID is not supported (and it always was [a work-around](https://docs.linuxserver.io/general/understanding-puid-and-pgid)). I don't know if it was maybe supported in the past.
2. I've just added the possibility to customize the default permissions - check the [README](https://github.com/tribut/homeassistant-docker-venv/blob/master/README.md#default-file-permissions). Let me know if you have problems (and don't forget to update the script!).
3. Before this repository was started, I've had a lengthy discussion with the developers of Home Assistant, see https://github.com/home-assistant/home-assistant/issues/24397 and https://github.com/home-assistant/home-assistant/pull/26471. They don't want to support running as non-root at this time.

**Comment by ptr727** [comment]
Thank you, I will try it out tonight.
I read your interaction with the hass devs and their reluctance to change, when as you discovered with this change, support in the baseline image would be trivial.
Anyway, thank you.

**Comment by ptr727** [comment]
Just confirming it works with UMASK.
I am now using LSIO code-server to edit config files, and the permissions work fine.

FYI, using LSIO version of code-server because unlike coder's original version, it honors PUID and GUID, does not run as root, but does have sudo support.
