### ISSUE TITLE
No longer working in HASS 2024.10.0

### ISSUE THREAD

**Issue by derekoharrow** [tribut/homeassistant-docker-venv#36]
Upgraded to HASS 2024.10.0 and this seems to stop many 3rd party HACS addons from working, including:

- hildebrandglow_dcc
- alexa_media
- uptime_kuma
- monitor_docker
- esxi_stats
- watchman
- pirateweather
- eufy_security

In the log file I get lots of messages like “Unable to install package… failed to create file /tmp/uv-…lock”

Removing venv from the startup and everything works fine again.

**Comment by tribut** [comment]
Thanks, HA moved to uv. I'll look into it!

**Comment by SaswatPadhi** [comment]
I just ran into this issue today, and I believe I've found the root cause and a fix for it.

As @tribut mentioned above, Home Assistant moved to `uv` in 2024.10. And they set `UV_SYSTEM_PYTHON=true` in their Docker image:
https://github.com/home-assistant/core/blob/6ee03460d6e67b9eba126141de65fca76b742275/Dockerfile#L10

The fix is to disable this, so `uv` doesn't use the system Python, but uses the venv's instead. You can test this by adding:

```
  -e "UV_SYSTEM_PYTHON=false"
```

to your `docker run` command line.

IMO, the `run` script should export this variable as `false` right after creating the venv.
